### ISSUE TITLE
Azure / AWS differences

### ISSUE THREAD

**Issue by hopitas** [databricks/terraform-databricks-lakehouse-blueprints#1]
Hi

Terraform scripts for creating databricks content seem to be different for AWS and Azure. Why? Is AWS more complete because Azure is work in progress? I'm thinking about building fs-lakehouse to azure and this guide /terraform template would be very helpful.

Thanks!

**Comment by rportilla-databricks** [comment]
@hopitas good callout. More robust Azure buildout is in the works and should be committed in the coming weeks.

**Comment by rportilla-databricks** [comment]
@hopitas , we've added a secure Azure Databricks architecture to protect data exfiltration that follows this blog. Let us know if you have any feedback - we are going to close this in case this satisfies your needs. https://www.databricks.com/blog/2020/03/27/data-exfiltration-protection-with-azure-databricks.html
