### ISSUE TITLE
AWS Databricks data exfiltration protection template

### ISSUE THREAD

**Issue by hwang-db** [databricks/terraform-databricks-lakehouse-blueprints#28]
To build a modular designed templates to deploy aws firewall & data exfiltration protection, reference to: https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/aws-e2-firewall-hub-and-spoke and https://www.databricks.com/blog/2021/02/02/data-exfiltration-protection-with-databricks-on-aws.html

**Comment by alexott** [comment]
we have this module in the examples
